version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_db" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pgdata:
